const typeSelectionStringArr =
{
    SKODA: [
        "Scala",
        "Kamiq",
        "Fabia",
        "Karoq",
        "Kodiaq",
        "Octavia",
        "Superb",
        "Citigo",
        "Enyaq",
        "Rapid",
    ],
    BMW: [
        "1 Series",
        "2 Series",
        "3 Series",
        "4 Series",
        "5 Series",
        "6 Series",
        "7 Series",
        "8 Series",
        "x1",
        "x2",
        "x3",
        "x4",
        "x5",
        "x6",
        "x7",
        "xm",
    ],
    MERCEDES: [
        "A-Class",
        "B-Class",
        "C-Class",
        "E-Class",
        "S-Class",
        "G-Class",
        "CLA",
        "CLS",
        "GLA",
        "GLB",
        "GLC",
        "GLE",
        "GLS",
    ],
    KIA: [
        "Sportage",
        "Stinger",
        "Rio",
        "Sorento",
        "Soul",
        "K900",
        "Optima",
        "Forte",
        "Niro",
    ],
    TOYOTA: [
        "Prius",
        "Corolla",
        "Camry",
        "4Runner",
        "Yaris",
        "C-HR",
        "Land Cruiser",
        "Land Cruiser Prado",
        "Highlander",
        "RAV4",
    ],
    VOLKSWAGEN: [
        "Golf",
        "ID.3",
        "Polo",
        "Up",
        "Arteon",
        "Bora",
        "ID.7",
        "Jetta",
        "Passat",
        "Caddy",
        "Amarok",
    ],
    SUBARU: [
        "BRZ",
        "Impreza",
        "Legacy",
        "WRX",
        "Forester",
    ],
    ISUZU: [
        "D-Max",
    ],
    DODGE: [
        "Challenger",
        "Charger",
        "Viper",
        "RAM",
        "Durango",
    ],
    FORD: [
        "Fiesta",
        "Mustang",
        "Explorer",
        " F-150",
        "Expedition",
        "Edge",
        "Ranger",
        "Bronco",
    ],
};


export default typeSelectionStringArr;