const typeSelection =
{
    SKODA: [
        { label: "Scala", },
        { label: "Kamiq", },
        { label: "Fabia", },
        { label: "Karoq", },
        { label: "Kodiaq", },
        { label: "Octavia", },
        { label: "Superb", },
        { label: "Citigo", },
        { label: "Enyaq", },
        { label: "Rapid", },
    ],
    BMW: [
        { label: "SKODA-BMW", },
        { label: "BMW2", },
        { label: "MERCEDES2", },
        { label: "KIA2", },
        { label: "TOYOTA2", },
        { label: "VOLKSWAGEN2", },
        { label: "GM2", },
        { label: "ISUZU2", },
        { label: "DODGE2", },
    ],
    MERCEDES: [
        { label: "SKODA-MERCEDES", },
        { label: "BMW3", },
        { label: "MERCEDES3", },
        { label: "KIA3", },
        { label: "TOYOTA3", },
        { label: "VOLKSWAGEN3", },
        { label: "GM3", },
        { label: "ISUZU3", },
        { label: "DODGE3", },
    ],
    KIA: [
        { label: "SKODA-KIA", },
        { label: "BMW2", },
        { label: "MERCEDES2", },
        { label: "KIA2", },
        { label: "TOYOTA2", },
        { label: "VOLKSWAGEN2", },
        { label: "GM2", },
        { label: "ISUZU2", },
        { label: "DODGE2", },
    ],
    TOYOTA: [
        { label: "SKODA-TOYOTA", },
        { label: "BMW2", },
        { label: "MERCEDES2", },
        { label: "KIA2", },
        { label: "TOYOTA2", },
        { label: "VOLKSWAGEN2", },
        { label: "GM2", },
        { label: "ISUZU2", },
        { label: "DODGE2", },
    ],
    VOLKSWAGEN: [
        { label: "SKODA-VOLKSWAGEN", },
        { label: "BMW2", },
        { label: "MERCEDES2", },
        { label: "KIA2", },
        { label: "TOYOTA2", },
        { label: "VOLKSWAGEN2", },
        { label: "GM2", },
        { label: "ISUZU2", },
        { label: "DODGE2", },
    ],
    GM: [
        { label: "SKODA-GM", },
        { label: "BMW2", },
        { label: "MERCEDES2", },
        { label: "KIA2", },
        { label: "TOYOTA2", },
        { label: "VOLKSWAGEN2", },
        { label: "GM2", },
        { label: "ISUZU2", },
        { label: "DODGE2", },
    ],
    ISUZU: [
        { label: "SKODA-ISUZU", },
        { label: "BMW2", },
        { label: "MERCEDES2", },
        { label: "KIA2", },
        { label: "TOYOTA2", },
        { label: "VOLKSWAGEN2", },
        { label: "GM2", },
        { label: "ISUZU2", },
        { label: "DODGE2", },
    ],
    DODGE: [
        { label: "SKODA-DODGE", },
        { label: "BMW2", },
        { label: "MERCEDES2", },
        { label: "KIA2", },
        { label: "TOYOTA2", },
        { label: "VOLKSWAGEN2", },
        { label: "GM2", },
        { label: "ISUZU2", },
        { label: "DODGE2", },
    ],
};


export default typeSelection;